### PR TITLE
Use MkDocs to generate doc website

### PR DESCRIPTION
**Pull request by marienfressinaud**
The process to generate the doc website is similar to the one for the main website + blog but use MkDocs (http://mkdocs.org/) which is designed for documentation. It is documented (see the README)

You can have a look to the result at http://dev.doc.freshrss.org

Three problems:

- Internationalisation is not handled by MkDocs itself so I have to generate two different websites (English and French) + add a home page to redirect to the wanted doc
- I had to reorganise the files because MkDocs doesn't support nested titles (at least, not like before)
- It introduces another Python program. I'm considering to create a script server-side to handle the generation

### CODE REVIEW

**Comment by marienfressinaud** [comment]
Fix https://github.com/FreshRSS/documentation/issues/5

**Comment by marienfressinaud** [comment]
Note I have to check everything has been moved from http://doc.freshrss.org, I just realised that some images are no present in the new version and maybe some pages have disappeared. But I stop to work on FRSS for today ;)

**Comment by Alkarex** [comment]
:+1:

**Comment by marienfressinaud** [comment]
Ready to merge! Ready to replace doc.freshrss.org! \o/

**Comment by Alkarex** [comment]
Good work!

**Pull request merged**
