### PR TITLE
[WIP] Added extension documentation in english

### PR DESCRIPTION
**Pull request by kevinpapst**
This is a first draft of the english extension documentation.
When ready, this PR will fix FreshRSS/FreshRSS#1386 and may also be related to FreshRSS/Extensions#1 .
I wanted to open the PR early, to be able to incorporate feedback from the team and community devs.

### CODE REVIEW

**Comment by Alkarex** [comment]
Thanks already :-)

**Comment by Alkarex** [comment]
Hello @kevinpapst 
Should we merge this draft, or do you have more in the pipeline? :-)

**Comment by kevinpapst** [comment]
Hey Alkarex, sorry I completely forgot about this PR.
Maybe it motivates someone to start documenting more infos or help them to understand the plugin API. You are welcome to merge it, if the current state is good enough for you.

**Comment by Alkarex** [comment]
OK, I have merged the current draft, which is already an improvement. Thanks so far. And of course, more input would be appreciated :-)

**Comment by marienfressinaud** [comment]
Deployed :)

**Pull request merged**
